### PR TITLE
Bump Atari envs version

### PR DESCRIPTION
**Pull request by carlosluis**
## Description
Bump version of Atari envs to match the latest in Gym (and Ale-py).

## Motivation and Context
Keeping up-to-date with latest changes in Atari envs.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
> Bump version of Atari envs to match the latest in Gym (and Ale-py).
> Keeping up-to-date with latest changes in Atari envs.

Hello,

I think there was a misunderstanding, see https://github.com/DLR-RM/stable-baselines3/pull/734#issuecomment-1030531584
and discussion in https://github.com/DLR-RM/stable-baselines3/pull/572#issuecomment-993701078

**Comment by carlosluis** [comment]
I see, missed that bit of context. Then I guess these changes will only be merged once performance of v5 are properly benchmarked. Could you confirm that's the case?

If yes, then I will close this PR as I wasn't planning on doing that right now.

**Comment by araffin** [comment]
> Then I guess these changes will only be merged once performance of v5 are properly benchmarked. Could you confirm that's the case?

There is more than that, some changes of v5 were quite arbitrary (see discussion with Jesse, starting here https://github.com/DLR-RM/stable-baselines3/pull/572#issuecomment-993701078) so I would tend to go for v4 with fixes (if that's possible), or v5 if v5 is benchmarked and compared to v4.
(I was also thinking about switching to env pool as it can be really fast for training on Atari games, but not in our tests as it would add an additional dependency)

**Comment by carlosluis** [comment]
Closing as unresolved. Read comments and associated issues for context

**Pull request closed without merging**
