### PR TITLE
Refactor HER

### LINKED ISSUE #284: [Bug] Infinize horizon tasks are handled like episodic tasks
Hi,
I wonder how to correctly use SAC with infinite horizon environments. I saw @araffin s answer to https://github.com/hill-a/stable-baselines/issues/776 where he points out that algorithms are step-based. Our environments could always return `done = False`, but we would have to reset the environment manually then. As a consequence, we would add transitions to the replay buffer going from the last state to the initial state, which is bad. 

Is the only solution to include a time-feature? That means messing with the `observation_space` size and handling dict spaces correctly + explaining what this "time-feature" is in papers. Let me know if I've missed a thread treating this issue already :smile:  
Greetings!

### 🐛 Bug / Background
My understanding is that SAC skips the target if `s'` is a terminal state:
```python
q_backup = replay_data.rewards + (1 - replay_data.dones) * self.gamma * target_q
```
In infinite horizon tasks, we wrap our env with `gym.wrappers.TimeLimit`, which sets `done = True` when the maximum episode length is reached. This stops the episode in SAC and the transition is saved in the replay buffer for learning. 

However, according to "Time Limits in Reinforcement Learning" (https://arxiv.org/abs/1712.00378), we should not see that last state as a "terminal" state, since the termination has nothing to do with the MDP. If we ignore this, we are doing "state aliasing" and violating the Markov Property.

### PR DESCRIPTION
**Pull request by araffin**
**NOTE: this branch will be merged with #243 not master**

## Description

Refactoring of HER (need to account for #297 ) using proper obs dict support.
We could also do the timelimit support (see #284 ) as we are breaking the replay buffer api (we need to provide upgrade script)

closes https://github.com/DLR-RM/stable-baselines3/issues/287 (image support for HER)
closes #284 (for off-policy algorithms)

TODO:
- [x] Check HER performance
- [x] Investigate offline replay buffer speed drop
- [x] Add documentation
- [x] Perf check for HER + TimeLimit handling (PyBullet)

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
@ferreirajoaouerj could you take a look at this PR? (this shoudl address your concern from https://github.com/DLR-RM/stable-baselines3/issues/297).
`HER` is now just a replay buffer class, so implementing multi-goal algorithms should be simpler, as one would need to define only a new buffer class.

**Comment by ferreirajoaouerj** [comment]
I'll take a look, thank you for addressing this feature.

**Comment by ferreirajoaouerj** [comment]
Sorry the delay. Nice that you managed to put everything into the replay buffer. The `select` in #297 function needs to change the `observation['desired_goal']` at the beginning of the episode. I was thinking about the least intrusive way to do that. Maybe the best option is to add an env wrapper, then is easy to also implement `reward` and we don't need to mess with `collect_rollouts` for each off-policy algo. Anyway, we could explore these options in `contrib` since the baseline HER is already up and running.

**Comment by araffin** [comment]
Thanks for taking a look =)

>he select in #297 function needs to change the observation['desired_goal'] at the beginning of the episode. I was thinking about the least intrusive way to do that. Maybe the best option is to add an env wrapper, then is easy to also implement reward and we don't need to mess with collect_rollouts for each off-policy algo. 

You are right, an env wrapper would be the way to go for changing/providing the desired goal at the beginning of an episode.

For the reward, the `compute_reward` is only used in the `HerReplayBuffer` so it should be quite easy to overwrite ;)

**Pull request merged**
