### PR TITLE
Policy Base for On-policy Algorithms (#412)

### LINKED ISSUE #412: [Feature Request] Flexible OnPolicyAlgorithm Policies
### 🚀 Feature

Flexible `OnPolicyAlgorithm` Policies to support more complex on policy algorithms.

### Motivation

I'm adding PPG to the Contrib library (an on-policy algorithm). In doing so, I have created a policy which extends `BasePolicy` (so that it can be registered as 'MlpPolicy'/'CnnPolicy') but the `OnPolicyAlgorithm` base class only accepts `ActorCriticPolicy` as the `policy_base`. I could extend the PPG policy from `ActorCriticPolicy` but this isn't supported by the `register_policy` method. The only option thus far is to register under a different policy name (e.g. 'PpgMlpPolicy') which goes against the design philosophy of the library.

### Pitch

Add `policy_base` input to the `OnPolicyAlgorithm` base class just like the `OffPolicyAlgorithm` base class.

### Alternatives

In `register_policy`, first check for extensions from subclasses of `BasePolicy` so other policy extentions can be registered under the standard string denominations.

### Additional context

NOTE: sorry for this bit being messy, I'm unsure how to make multi-lines of code layout :(

This is what the new `OnPolicyAlgorithm` definition would look like:
```python
def __init__(
        self,
        policy: Union[str, Type[ActorCriticPolicy]],
        env: Union[GymEnv, str],
        learning_rate: Union[float, Schedule],
        n_steps: int,
        gamma: float,
        gae_lambda: float,
        ent_coef: float,
        vf_coef: float,
        max_grad_norm: float,
        use_sde: bool,
        sde_sample_freq: int,
        **policy_base: Type[BasePolicy] = ActorCriticPolicy,**
        tensorboard_log: Optional[str] = None,
        create_eval_env: bool = False,
        monitor_wrapper: bool = True,
        policy_kwargs: Optional[Dict[str, Any]] = None,
        verbose: int = 0,
        seed: Optional[int] = None,
        device: Union[th.device, str] = "auto",
        _init_setup_model: bool = True,
        supported_action_spaces: Optional[Tuple[gym.spaces.Space, ...]] = None,
    ):

        super(OnPolicyAlgorithm, self).__init__(
            policy=policy,
            env=env,
            policy_base=policy_base,
            learning_rate=learning_rate,
            policy_kwargs=policy_kwargs,
            verbose=verbose,
            device=device,
            use_sde=use_sde,
            sde_sample_freq=sde_sample_freq,
            create_eval_env=create_eval_env,
            support_multi_env=True,
            seed=seed,
            tensorboard_log=tensorboard_log,
            supported_action_spaces=supported_action_spaces,
        )

```
A rudimentary example of `register_policy` check for subclasses:

```python
    sub_class = None
    for cls in ActorCriticPolicy.__subclasses__():
        if issubclass(policy, cls):
            sub_class = cls
            break
    if sub_class is None:
        for cls in BasePolicy.__subclasses__():
            if issubclass(policy, cls):
                sub_class = cls
                break
    if sub_class is None:
        raise ValueError(
            f"Error: the policy {policy} is not of any known subclasses of BasePolicy!"
        )
```
### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

### PR DESCRIPTION
**Pull request by 09tangriro**
## Description
Added `policy_base` to the `OnPolicyAlgorithm` class definition, including a description in the method description.

## Motivation and Context

closes #412 
- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Can you quickly make sure that loading models saved with the pre-PR code can be loaded with this post-PR code? I can not think of other new tests that we we would require here.

**Comment by 09tangriro** [comment]
Hi, I just ran a little notebook test which seemed to work fine, code I used is below:

image

I set up agent using the pre PR code and model loads given the post PR code, is this sufficient?

**Comment by Miffyli** [comment]
Sounds good 👍 . I will review this properly tomorrow with a rested head.

**Review by Miffyli — APPROVED** [review]
LGTM! Thanks for the PR 👍

**Pull request merged**
