### PR TITLE
#1258 QC_SANE 

### PR DESCRIPTION
**Pull request by surbhigupta1908**
QC_SANE implementation.
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by surbhigupta1908** [comment]
make lint, and make type were not successful.
My script is creating some variables on the fly because of that "make lint" and "make type"  throw error (like local variable not used, library imported bu
type
lint
t not used etc.) .

**Comment by qgallouedec** [comment]
Hi @surbhigupta1908, thanks for your contribution. As explained by arafin here: https://github.com/DLR-RM/stable-baselines3/issues/1258#issuecomment-1370084428, the algorithm you propose would be more appropriate in the experimental repo. See its description [here](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib#what-is-sb3-contrib). So I close this PR. (the work is not lost, the integration in sb3-contrib is identical).

Personally, I think it would be much more relevant to mention your project in the [dedicated documentation page](https://stable-baselines3.readthedocs.io/en/master/misc/projects.html). Tell me what you think about it.

**Comment by araffin** [comment]
@qgallouedec yes, i tend to agree with you.

**Comment by surbhigupta1908** [comment]
Ok, thanks!! 
Understood.

**Pull request closed without merging**
