### PR TITLE
Small docstring improvements related to the notion of Rollout

### LINKED ISSUE #201: [question/doc] Name of the class RolloutBuffer
on-policy algorithms in this library use a buffer called "RolloutBuffer"

In RL the term rollout is usually used in the context of model-based RL and planning. However, as it is used here its just a special kind of experience replay buffer where all elements are produced by playing out one policy on the environment. In planning, the rollout also has a consecutive quality to it. Also "rollout buffer" is permutated randomly.

Hence i would suggest to rename the buffer in a different way to prevent misconception or at least clarify this in the class documentation.

If you broadly follow along my argument i could make a suggestion and perhaps create a PR.

### PR DESCRIPTION
**Pull request by stheid**
Small changes in documentation and function naming

## Description

Improved documentation related to the term "rollout"

## Motivation and Context
closes #201 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] Updated documentation (developer.rst)
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)

`make type` fails in `common/monitor.py`, but not in files i modified

### CODE REVIEW

**Comment by araffin** [comment]
Hello,

thanks for the PR, I think there was a misunderstanding with @Miffyli in #201 .
We agreed on updating the docstrings to clarify things but wanted to keep the names.

the failure is due to a failure in building the documentation (`make doc`)

**Comment by stheid** [comment]
Understood. i will take care off that next week.

**Comment by stheid** [comment]
when i run `make doc` i get completely different errors than here, therefore i will need to debug it via your CI

`/usr/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py:docstring of stable_baselines3.common.logger.SummaryWriter.add_audio:9:Unexpected indentation.
`

**Comment by araffin** [comment]
Please don't forget to update the changelog ;) (and add your name at the bottom)

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
