### PR TITLE
Removed shared layers in mlp_extractor

### PR DESCRIPTION
**Pull request by AlexPasqua**
## Description

Removed option to have shared layers in the `mlp_extractor`.

`net_arch`:
1. list of integers: creates policy and value nets with the same amount and size of layers (2 identical, but separate networks);
2. `dict(pi=[<list of integers>], vf=[<list of integers>])`: allows to specify the amount and size of the layers in the policy and value nets independently.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)
According to #1148 ([this comment](https://github.com/DLR-RM/stable-baselines3/pull/1148#issuecomment-1359429073))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by AlexPasqua** [comment]
On my PC the documentation builds. Here it doesn't, but the problem comes from a file that I haven't modified.

**Comment by qgallouedec** [comment]
> On my PC the documentation builds. Here it doesn't, but the problem comes from a file that I haven't modified.

It's not linked to your PR, see #1290

**Review by araffin — APPROVED** [review]
LGTM, thanks =)
could you also open the associated PR in SB3 contrib?
(I will do an alpha release in the meantime)

**Comment by AlexPasqua** [comment]
> LGTM, thanks =) could you also open the associated PR in SB3 contrib? (I will do an alpha release in the meantime)

Sure, by tonight I'll open it

**Comment by araffin** [comment]
>  Is anything needed in the rl-zoo?

just updating SB3 contrib version I guess

**Pull request merged**
