### PR TITLE
Deprecation of shared layers in `MlpExtractor`

### LINKED ISSUE #1161: [Feature Request] Deprecate shared networks
### 🚀 Feature

See https://github.com/DLR-RM/stable-baselines3/pull/1148
"Looking at the code and thinking for the future, it would probably make sense to always separate the networks after the feature extractor (so deprecate and remove the shared network in the mlp)."

This is more a request for consistency and less flexibility for more readability.
Currently part of the mlp for PPO/A2C can be shared, that results in quite complex code for creating the mlp and not so simple code when creating a custom policy.
As a result, the type of `net_arch` is inconsistent between on-policy algorithms and off-policy algorithms.

In addition to that, for the mlp, by experience, separate networks always perform better, and you don't lose much in performance (wall clock).

### Motivation

That would allow to have a cleaner distinction between actor and critic and have consistent code with the off-policy algorithms.

This should also make creating custom policy more easily.

### Pitch

Deprecate and then remove that feature.

I'm happy to change my mind if the benefit of this feature is backed by experimental evidences.

### Alternatives

Do nothing, keep as is.

### Additional context

_No response_

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

### PR DESCRIPTION
**Pull request by AlexPasqua**
## Description

Added deprecation warning in `MlpExtractor` in case there are shared layers in `net_arch`, i.e. `net_arch` starts with an integer

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)
In accordance with #1161

closes #1161 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by AlexPasqua** [comment]
I get a "Function is too complex (C901)" when doing `make lint`, but I don't think it has to do with my modifications since I didn't change `BaseAlgorithm.load`.
This is the output I receive for `make lint`:
```bash
# stop the build if there are Python syntax errors or undefined names
# see https://lintlyci.github.io/Flake8Rules/
flake8 stable_baselines3/ tests/ docs/conf.py setup.py --count --select=E9,F63,F7,F82 --show-source --statistics
0
# exit-zero treats all errors as warnings.
flake8 stable_baselines3/ tests/ docs/conf.py setup.py --count --exit-zero --statistics
stable_baselines3/common/base_class.py:620:5: C901 'BaseAlgorithm.load' is too complex (17)
1     C901 'BaseAlgorithm.load' is too complex (17)
1
```

**Comment by AlexPasqua** [comment]
@araffin shall I then do an equivalent PR in SB3-contrib?

**Comment by araffin** [comment]
> shall I then do an equivalent PR in SB3-contrib?

Yes, please =)

**Review by araffin — COMMENTED** [review]
LGTM, thanks =)
I will merge once the PR in SB3 contrib and RL Zoo are opened.

**Review by araffin — APPROVED** [review]

**Pull request merged**
