### PR TITLE
Standardized the use of ``"`` for string representation

### PR DESCRIPTION
**Pull request by qgallouedec**
In #780, some changes are out of the scope of the PR. In particular the use of ``"`` for string representation in the documentation.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [ ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Review by araffin — COMMENTED** [review]
Thanks =) do you have a command for that or did you make the changes manually?

The failure is due to importlib metadata, see what I did in #780 (one of the last commit)

**Comment by qgallouedec** [comment]
> Thanks =) do you have a command for that or did you make the changes manually?

Manually, mostly ... ;)

> The failure is due to importlib metadata, see what I did in https://github.com/DLR-RM/stable-baselines3/pull/780 (one of the last commit)

We should solve this problem in another PR, what do you think?

**Comment by qgallouedec** [comment]
I've just checked: no need for a twin PR in rl-baselines3-zoo nor in stable-baselines3-contrib

**Comment by araffin** [comment]
> We should solve this problem in another PR, what do you think?

I'm fine with solving it here or in another PR that will be merged soon.

**Review by araffin — APPROVED** [review]
LGTM =)

**Pull request merged**
