### PR TITLE
Fix exception cause in base_class.py

### PR DESCRIPTION
**Pull request by cool-RR**
## Description
Fix exception cause in base_class.py. This means that when there are chained exceptions, the text between the two exceptions describes their relationship correctly.

This addresses https://github.com/DLR-RM/stable-baselines3/issues/941 but doesn't solve all the instances, just one for starters. After it's accepted I'll do the rest.

For more context, see https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with
## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [X] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [X] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [X] I have reformatted the code using `make format` (**required**)
- [X] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [X] I have ensured `make pytest` passes. (**required**)
- [X] I have ensured `make type` passes. (**required**)
- [X] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by cool-RR** [comment]
Sorry. I finished running everything now and filled up the template.

**Comment by cool-RR** [comment]
Sounds good, I now fixed the exception causes all over the codebase.

**Review by Miffyli — APPROVED** [review]
LGTM! Thanks for the PR and thanks for introducing me to this concept which I will use from now on :)

**Comment by cool-RR** [comment]
My pleasure.

**Pull request merged**
