### PR TITLE
Update GAE computation docstring

### PR DESCRIPTION
**Pull request by shyamal-anadkat**
## Description
Fix typo in buffers.py documentation 

Uses Generalized Advantage Estimation (https://arxiv.org/abs/1506.02438)
        to compute the advantage. To obtain vanilla advantage (A(s) = R - V(S))
        where R is the discounted reward with value bootstrap,
        set ``gae_lambda=0`` during initialization.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Hey. Thanks for the PR! Please fill in the whole PR template (even if the changes are small) :)

**Comment by araffin** [comment]
Screenshot_20211108-225642

**Comment by Miffyli** [comment]
Aah, right. I was confused with "what is the vanilla advantage": I assumed `r + V(s_t+1) - V(s_t)` is the "vanilla" advantage estimation, as it seems most obvious in the current day of bootstrapping things. From A2C etc side the former (lambda=0) seems "vanilla". Should have read rest of the same docstring...

How about clarying the docstring regarding what is "vanilla"? @shyamal-anadkat  what was the confusing part for you?

**Comment by shyamal-anadkat** [comment]
Thanks for the updates @araffin

**Pull request merged**
