### PR TITLE
Link to full imitation docs

### PR DESCRIPTION
**Pull request by qxcv**
## Description

Updates the `imitation` docs page to provide a prominent link to the full `imitation` docs, which are more detailed.

## Motivation and Context

Right now `imitation` page in the SB3 docs outrank the actual `imitation` docs on Google. I was introducing someone to the imitation lib, and thought it was a bit confusing that the top search result was just a short explainer page in the SB3 docs instead of the full library-specific readthedocs page. This change might help avoid some confusion.

(I haven't created an issue for this, since I discussed it with @AdamGleave already, but I can create one if needed.)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**). (I skipped this, since it's just a docs change)
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by AdamGleave** [comment]
The diff itself looks fine, but I just noticed the example code in the docs doesn't work: `expert_demos` no longer exists. It's been renamed to `train_rl`, but I think probably should just use `eval_policy` to generate the rollouts (can use experts saved to HuggingFace).

Probably worth fixing that as well in this PR?

**Comment by qxcv** [comment]
Nice catch! How much do you think it makes sense to keep those executable examples given that there are complete/up-to-date examples in the imitation docs? It's easy to fix this issue, but I'd be worried about code breakage happening again given that these docs are part of a different repo to the rest of imitation.

**Comment by AdamGleave** [comment]
Good point, probably fine to just point to a relevant part of the docs, I think it was largely cribbed from https://imitation.readthedocs.io/en/latest/getting-started/first-steps.html anyway

**Comment by qxcv** [comment]
Okay, I pulled out the existing instructions and linked to the quickstart guide instead. Screenshot of the new page:

image

**Review by AdamGleave — APPROVED** [review]
LGTM

**Pull request merged**
