### PR TITLE
Escape tensorboard log name

### PR DESCRIPTION
**Pull request by quantitative-technologies**
Otherwise utils does not recognize the log.

In the function `get_latest_run_id` the `log_name` parameter is now escaped. 

## Motivation and Context

Suppose that a `log_name='filename[16, 16]'` is used for the tensorboard log name. The first run will use the subdirectory `filename[16, 16]_1`. However, because `[` is a special character, without this change, on the second run `get_latest_run_id` will not recognize the first run and will again use the same subdirectory ending in `_1`, instead of incrementing to `_2`. 

This change fixes the problem. 

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [ x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

It tried but got `/bin/bash: pytype: command not found`. Google says `pytype` is a python library?

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Hey! Please complete the steps in the PR template, and we would still like to have an issue on the topic for book-keeping and discussing solutions :)

**Comment by quantitative-technologies** [comment]
> PR template

Hello,

I have updated the changelog by adding a line to the Bug Fixes section of the most recent release.

The PR steps are all completed except for "I have raised an issue to propose this change..". This does not fix an existing issue. Please let me know if you need me to make a new issue.

**Comment by araffin** [comment]
Hello,
Please update black to the latest version of revert that commit: https://github.com/DLR-RM/stable-baselines3/pull/796/commits/529a275d9475f85ef031038a8f3565f7301e5371 (you should format only the file that you changed)

> Please let me know if you need me to make a new issue.

yes, please, we need to discuss the issue first normally before any PR.

> The PR steps are all completed except

A test is missing too

**Comment by quantitative-technologies** [comment]
> Hello, Please update black to the latest version of revert that commit: [529a275](https://github.com/DLR-RM/stable-baselines3/commit/529a275d9475f85ef031038a8f3565f7301e5371) (you should format only the file that you changed)
> 
> > Please let me know if you need me to make a new issue.
> 
> yes, please, we need to discuss the issue first normally before any PR.
> 
> > The PR steps are all completed except
> 
> A test is missing too

I did the reversion, and also raised an issue as a feature request: https://github.com/DLR-RM/stable-baselines3/issues/817,
though perhaps it should have been raised as a bug.

**Comment by araffin** [comment]
You did the pull request using master branch, so I couldn't push changes...
Will be closed by https://github.com/DLR-RM/stable-baselines3/pull/857

**Pull request closed without merging**
