### PR TITLE
replaced KEY_TO_GOAL_STRATEGY[my_strategy] by GoalSelectionStrategy[m…

### PR DESCRIPTION
**Pull request by hbonnavaud**
…y_strategy.upper()]

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [ ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by hbonnavaud** [comment]
#1627

**Comment by qgallouedec** [comment]
Thanks for the PR,
Please make sure to update the changelog

**Comment by hbonnavaud** [comment]
I have errors using the make commands, and at this point, it is faster to make the modifications than to fill this form. I'm done with it.

**Comment by araffin** [comment]
Hello,
what error did you get?
i hope you would understand that the contributing guide and associated checklist is not there because we love to tick boxes but rather because we want to ensure code quality for our users.

**Comment by hbonnavaud** [comment]
yes I understand and this is a good practice but I don't have enough free time for that.

**Pull request closed without merging**
