### PR TITLE
Remove recurrent policies from A2C docs

### LINKED ISSUE #471: A2C documentation lists recurrent policies as enabled
### 📚 Documentation

Recurrent policies are not supported yet as of (#160 (comment)), but the [docs](https://stable-baselines3.readthedocs.io/en/master/modules/a2c.html) say that A2C supports them. I suggest changing it to avoid misleading.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

### PR DESCRIPTION
**Pull request by bstee615**
Recurrent policies are not supported yet as of (https://github.com/DLR-RM/stable-baselines3/issues/160#issuecomment-694756355), but the docs say that A2C supports them. Changing it to avoid misleading.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

closes #471 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Good catch! We must be blind having missed this completely all this time :')

Please do all items on the checklist (changelogs and contributors).

**Comment by Miffyli** [comment]
Note: You do not need to open a new PR to do this. You can do more commits to your existing branch in your fork :)

**Comment by bstee615** [comment]
> Good catch! We must be blind having missed this completely all this time :')
> 
> Please do all items on the checklist (changelogs and contributors).

Will do. Sorry! Didn't mean to open the PR until I finished the contributor guide.

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
