### PR TITLE
Upgrade package versioning to use Poetry

### PR DESCRIPTION
**Pull request by HadiSDev**
Upgraded to use poetry
## Description

- Dockerfiles uses poetry
- pyproject.toml changes to included relevant poetry settings
- removed old setup files
- Scripts updates
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

it is an old issue, but I put the effort to make it work anyway: https://github.com/DLR-RM/stable-baselines3/issues/545

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by HadiSDev** [comment]
Only thing missing is to add the credentials to poetry for publishing the package:
https://python-poetry.org/docs/repositories/#publishable-repositories

**Comment by rhaps0dy** [comment]
Working with CUDA Pytorch using Poetry is quite hard in my experience. Poetry insists on reinstalling it to the CPU version.

I also think you're [not supposed to commit the `poetry.lock` for libraries](https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control).

Nowadays pip also lets you specify dependencies directly in `pyproject.toml`. Take a look at [the `tuned-lens` `pyproject.toml` for example](https://github.com/AlignmentResearch/tuned-lens/blob/main/pyproject.toml#L12-L49).

**Comment by HadiSDev** [comment]
@rhaps0dy Thanks for taking a look at my PR <3 So just to respond to the points you made:
- It is part of the poetry convention to push the lock file to the repo as it is much faster to install the packages with that and it secures the versions platform independent. See [SO forum](https://stackoverflow.com/questions/61037557/should-i-commit-lock-file-changes-separately-what-should-i-write-for-the-commi/74045098#74045098)

- The pytorch CUDA issue is more or less fixed. Poetry will install the CUDA version by default unless you are on a macos system.
- If a use wants to use another torch version like 2.0 or only cpu version, then can specify that in their own project lock or requirement file with no issues.

**Comment by HadiSDev** [comment]
Okay I think it is better to actually remove the .lock file. Will make it easier for developers as we all have different machines. As for specifying the torch version, say for example I wanted to use torch 2.0.0 and I want to use the cuda 11.8 version. Then I would add the following to the pyproject file:

[[tool.poetry.source]]
name = "torch-gpu"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
torch = {version = "2.0.1+cu118", source = "torch-gpu"}


If the user wants to use pip package manager in his project he can also just manually install torch:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by araffin** [comment]
Just to make sure we're on the same page, the result of the discussion in https://github.com/DLR-RM/stable-baselines3/issues/545 still stands, in the sense that poetry does not seem to be necessary for SB3, although nothing prevents you from setting it up yourself (as you do in this PR).

**Comment by HadiSDev** [comment]
@araffin okay :( Poetry did help finding some version mismatch between the packages, so I think it is useful but this is not my repo so I respect your decision. I will keep my code saved in case you change your mind so we don't have to redo it, just in case :)

**Pull request closed without merging**
