### PR TITLE
Draft PR commit

### PR DESCRIPTION
**Pull request by Melanol**
#975

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Melanol** [comment]
Excuse me, is it normal to fail 24 tests after changing nothing?

**Comment by qgallouedec** [comment]
From what I can see, none of the tests failed

**Comment by Melanol** [comment]
I ran `make pytest`, and the output is `24 failed, 529 passed, 15 skipped, 1 deselected, 4 warnings`.

**Comment by Melanol** [comment]
Here is the list of everything that fails on my machine:

tests/test_her.py::test_save_load[False-False-SAC]
tests/test_her.py::test_save_load[False-False-TD3]
tests/test_her.py::test_save_load[False-False-DDPG]
tests/test_her.py::test_save_load[False-False-DQN]
tests/test_her.py::test_save_load[False-True-SAC]
tests/test_her.py::test_save_load[True-False-SAC]
tests/test_her.py::test_save_load[True-False-TD3]
tests/test_her.py::test_save_load[True-False-DDPG]
tests/test_her.py::test_save_load[True-False-DQN]
tests/test_her.py::test_save_load[True-True-SAC]
tests/test_run.py::test_train_freq[4]
tests/test_run.py::test_train_freq[train_freq1]
tests/test_run.py::test_train_freq[train_freq2]
tests/test_save_load.py::test_save_load[PPO]
tests/test_save_load.py::test_save_load[TD3]
tests/test_save_load.py::test_save_load[SAC]
tests/test_save_load.py::test_save_load[DDPG]
tests/test_save_load.py::test_set_env[PPO]
tests/test_save_load.py::test_set_env[TD3]
tests/test_save_load.py::test_set_env[SAC]
tests/test_save_load.py::test_set_env[DQN]
tests/test_save_load.py::test_set_env[DDPG]
tests/test_save_load.py::test_save_load_pytorch_var
tests/test_save_load.py::test_save_load_env_cnn[TD3]

I will try to investigate.

**Comment by Melanol** [comment]
It seems like all errors are the same:

            if capturable:
                assert param.is_cuda and step_t.is_cuda, "If capturable=True, params and state_steps must be CUDA tensors."
            else:
>               assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
E               AssertionError: If capturable=False, state_steps should not be CUDA tensors.

../../miniconda3/envs/stable-baselines3/lib/python3.10/site-packages/torch/optim/adam.py:255: AssertionError

I downgraded to Python 3.9, and nothing changed.

**Comment by qgallouedec** [comment]
Which ones? What error?

**Comment by Melanol** [comment]
@qgallouedec I solved it and deleted unnecessary comments.

**Comment by araffin** [comment]
Closing as it seems that there is no issue but rather a lack of clarity in the documentation: https://github.com/DLR-RM/stable-baselines3/issues/975#issuecomment-1198992211

I would be happy to receive a PR that update and and clarify the docs =)

**Pull request closed without merging**
