### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by qgallouedec**
## Description

Python 3.10 is stable. See https://devguide.python.org/versions/

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [x] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
Well, it's more "test support", I'm currently using python 3.11 locally ^^` (with pytorch nightly)
Almost everything works =) (SB3 and SBX fully working, just some envs/packages missing)

**Comment by qgallouedec** [comment]
Should we delay this upgrade then?

**Comment by araffin** [comment]
> Should we delay this upgrade then?

For python 3.10 should be fine, no? (I was thinking about adding it to the CI when we drop python 3.7, end of life is in 6 months).
For python 3.11, yes we need to wait that core dependencies upgrade but it actually doesn't prevent from using SB3 with python 3.11.

**Comment by qgallouedec** [comment]
> For python 3.10 should be fine, no? (I was thinking about adding it to the CI when we drop python 3.7, end of life is in 6 months).

I think so.

> For python 3.11, yes we need to wait that core dependencies upgrade but it actually doesn't prevent from using SB3 with python 3.11.

Great, that's reassuring, so we shouldn't have any bad surprises.

**Review by araffin — APPROVED** [review]

**Pull request merged**
