### PR TITLE
Fix check_env for Sequence observation space

### LINKED ISSUE #1683: [Bug]: stable_baselines3.common.env_checker.check_env throws misleading error
### 🐛 Bug

stable_baselines3.common.env_checker.check_env throws misleading error when using [Sequence](https://gymnasium.farama.org/main/api/spaces/composite/#gymnasium.spaces.Sequence) as observation space.

```
 spaces.Sequence(spaces.Discrete(8)).sample()
```
returns
```
(3, 4, 4)
```

Thus, observation should be a tuple, yet check_env throws an error that it should not be. If Stable-Baselines doesn't support this observation space, then _check_unsupported_spaces method should be updated to throw an error that Sequence is unsupported. Or if it is supported, then the _check_obs method should be updated so that it wouldn't throw an error.

### Code example

```python
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3.common.env_checker import check_env

class SomeEnv(gym.Env):
    metadata = {"render_modes": ["human"], "render_fps": 2}
    
    def _get_obs(self):
        return self.items
    
    def _get_info(self):
        return {}
    
    def __init__(self, render_mode=None, size=5):
        self.observation_space = spaces.Sequence(spaces.Discrete(8))
        
        self.action_space = spaces.MultiDiscrete(8*[4] + [5])

        assert render_mode is None or render_mode in self.metadata["render_modes"]
        self.render_mode = render_mode

        self.clock = None
    
    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.step_count = 0
        self.items = self.observation_space.sample()
            
        print(self.items)
        observation = self._get_obs()
        info = self._get_info()

        return observation, info
    
    def step(self, action):
        observation = self._get_obs()
        reward = 1
        terminated = True
        truncated = False
        info = {}
        return observation, reward, terminated, truncated, info 

some_env = SomeEnv()
check_env(some_env)
```

### Relevant log output / Error message

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19204/2147117518.py in <module>
      1 some_env = SomeEnv()
----> 2 check_env(some_env)

~\miniconda3\lib\site-packages\stable_baselines3\common\env_checker.py in check_env(env, warn, skip_render_check)
    442 
    443     # ============ Check the returned values ===============
--> 444     _check_returned_values(env, observation_space, action_space)
    445 
    446     # ==== Check the render method and the declared render modes ====

~\miniconda3\lib\site-packages\stable_baselines3\common\env_checker.py in _check_returned_values(env, observation_space, action_space)
    279                 raise AssertionError(f"Error while checking key={key}: " + str(e)) from e
    280     else:
--> 281         _check_obs(obs, observation_space, "reset")
    282 
    283     # Sample a random action

~\miniconda3\lib\site-packages\stable_baselines3\common\env_checker.py in _check_obs(obs, observation_space, method_name)
    178     """
    179     if not isinstance(observation_space, spaces.Tuple):
--> 180         assert not isinstance(
    181             obs, tuple
    182         ), f"The observation returned by the `{method_name}()` method should be a single value, not a tuple"

AssertionError: The observation returned by the `reset()` method should be a single value, not a tuple
```

### System Info

Gymnasium version: '0.29.1'
Stable-Baselines 3 version: '2.1.0'

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

### PR DESCRIPTION
**Pull request by corentinlger**
Add a condition to check if observation space of an environment is Sequence in the "_check_unsupported_spaces". Add a condition to stop the "check_env" function is this type of obs space is detected (only if warn=True).

Should I solve the issue a different way ?

I had a segmentation fault error while running make pytest.

## Description

closes #1683 

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
Hello,

> Should I solve the issue a different way ?

looks good but you should add a test.

**Comment by corentinlger** [comment]
I launched the test and it was ok up until 94%. Then I had a segmentation fault (error 139) :

"""
tests/test_vec_envs.py::test_render[DummyVecEnv] Fatal Python error: Segmentation fault
"""

I didn't see any similar case in the issues. Do you know why it could have happened  ? (I already had this problem when I launched the test for another issue)

**Comment by araffin** [comment]
>  tests/test_vec_envs.py::test_render[DummyVecEnv] Fatal Python error: Segmentation fault

you can safely ignore that test.

**Comment by corentinlger** [comment]
> looks good but you should add a test.

I am kind of confused about the test you talked about . You meant adding an automatic test in the `test_env_checker.py` file ?

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Comment by corentinlger** [comment]
You're welcome ! Thanks for the lib (:

**Pull request merged**
