### PR TITLE
New bug report issue form

### PR DESCRIPTION
**Pull request by qgallouedec**
## Description

See #1110
To see how it looks like, check out https://github.com/qgallouedec/fake_repo_for_issue_form/issues/new/choose

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by qgallouedec** [comment]
I'm not sure about the feature request form. It seems pretty rigid to me.

**Review by araffin — APPROVED** [review]
LGTM =)

**Comment by araffin** [comment]
> I'm not sure about the feature request form. It seems pretty rigid to me.

well, only one of the field is required, so should be fine.
And then there is the issue comments to be more flexible.

**Comment by araffin** [comment]
@qgallouedec after testing them, I think we should add a new block for tracebacks, no? (it is not possible to resize the textarea block :/)

**Comment by qgallouedec** [comment]
Something like this?

Screenshot 2022-10-13 at 18 11 05

Why not, I don't have a strong opinion on the matter. Tell me, I can do it if you want.

> it is not possible to resize the textarea block :/

I think you can, look at the image.

**Comment by araffin** [comment]
> I think you can, look at the image.

weird, it was somehow not working when I tested on your repo, but now it does work.

**Pull request merged**
