### PR TITLE
Add Gitlab CI

### PR DESCRIPTION
**Pull request by araffin**
## Description

Add continuous integration using Gitlab-CI.

## Motivation and Context

Addresses part of #1 .

### CODE REVIEW

**Comment by AdamGleave** [comment]
Curious why you chose GitLab? I mostly use CircleCI these days and found it a big improvement on Travis but I've not tried GitLab/Azure Pipelines and some of the other new players.

**Comment by araffin** [comment]
>Curious why you chose GitLab? 

Good point, the thing is I'm in discussion with my institute admins because travis/cicle ci/codacy require additional permissions, but I wanted to setup CI as soon as possible anyway.
So, I found that Gitlab had a nice integration with Github ;)

>mostly use CircleCI these days and found it a big improvement on Travis but I've not tried GitLab/Azure Pipelines and some of the other new players.

That was something I've seen and wanted to ask you, what is best? and why CircleCI?

**Comment by araffin** [comment]
@AdamGleave I will merge it as it is needed for any further PR, but we can continue the discussion here ;)

**Comment by AdamGleave** [comment]
> Good point, the thing is I'm in discussion with my institute admins because travis/cicle ci/codacy require additional permissions, but I wanted to setup CI as soon as possible anyway.
> So, I found that Gitlab had a nice integration with Github ;)
OK, makes sense -- thanks for setting up CI.
> 
> > mostly use CircleCI these days and found it a big improvement on Travis but I've not tried GitLab/Azure Pipelines and some of the other new players.
> 
> That was something I've seen and wanted to ask you, what is best? and why CircleCI?

I like CircleCI since it easily supports parallelizing across nodes (up to 4 nodes free), and -- if you pay -- you can run on machines with more resources. This is very useful for large and slow test suites, such as if you're actually training mini-ML models as part of the suite.

It seems much more actively developed than Travis and has a better UI and generally more features.

Pipelines looks pretty nice and I've seen a few open-source projects migrate to this but I don't have any hands-on experience with it.

**Comment by araffin** [comment]
>Pipelines looks pretty nice and I've seen a few open-source projects migrate to this but I don't have any hands-on experience with it.

Pipeline are nice but build for external PR are not automatic :/ (I need to create an internal branch that corresponds to each PR)
So I guess I will ask the admins for CircleCI integration.

**Pull request merged**
