### PR TITLE
change timestamp to episode for logging

### PR DESCRIPTION
**Pull request by theSquaredError**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by qgallouedec** [comment]
Great @theSquaredError. Now you just need to update the changelog (docs/misc/changelog). Add a line after the line 47. You can also add your name to the list of contributors at the end of the changelog!

**Comment by theSquaredError** [comment]
I have updated changelog

**Comment by qgallouedec** [comment]
Great, now let's see if the CI passes. In the meantime, can you check if there is a similar issue in the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) or in the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo)?

**Comment by theSquaredError** [comment]
There is same issue in[ SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib)

**Comment by qgallouedec** [comment]
Thanks, could you also open a PR on sb3 contrib repo?

**Review by qgallouedec — APPROVED** [review]

**Comment by qgallouedec** [comment]
Thanks for your (first) contribution @theSquaredError 🎉

**Comment by theSquaredError** [comment]
Hi @qgallouedec , I have opened PR for sb3 contrib repo. Can you tell me some other issues which I can solve as the next thing and what to do to understand the library better?

**Comment by qgallouedec** [comment]
Thank you for wanting to help improve the library. I recommend that you check out [the "help wanted" questions] (https://github.com/DLR-RM/stable-baselines3/labels/help%20wanted). Also feel free to suggest improvements, like cleaning up the doc (some parameters lack description for example).

**Pull request merged**
