### PR TITLE
Fix type hints for DQN

### PR DESCRIPTION
**Pull request by araffin**
## Description

Also fixed a potential bug found by mypy for DQN predict.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [ ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by qgallouedec** [comment]
I feel like we are moving the problem elsewhere with the `assert isinstance`... But I have no idea how to make it work in another way.
I don't mind approving even though I'm not completely satisfied with this solution.

**Comment by araffin** [comment]
> I feel like we are moving the problem elsewhere with the assert isinstance... But I have no idea how to make it work in another way.

this is partially true, at first I replaces `self.policy = None` with the right type but it created more issues.
For the features extractor, it comes from the fact that it is defined dynamically by calling `self.feature_extractor_class()`, maybe adding a `self.features_extractor: BaseExtractor` in the constructor will help, let me try that.

**Comment by araffin** [comment]
>  For the features extractor, it comes from the fact that it is defined dynamically by calling self.feature_extractor_class(), maybe adding a self.features_extractor: BaseExtractor in the constructor will help, let me try that.

actually here the error comes from MyPy not understanding that features extractor is definitely not `None` once the constructor of `QNetwork` has been called.

I fixed the other issues for the policy and fixed a potential bug with DQN when using dictionary and images.

Note: The `isinstance()` actually follows https://mypy.readthedocs.io/en/stable/type_narrowing.html.

**Review by qgallouedec — APPROVED** [review]

**Comment by qgallouedec** [comment]
> @qgallouedec do you think you will have time to re-review this one this week?

Sorry I missed your comment. I've nothing to add :)

**Comment by araffin** [comment]
> Sorry I missed your comment. I've nothing to add :)

no worry, thanks =)
I'll prepare the PR for SB3 contrib (bug fix only for QR-DQN) and merge

**Pull request merged**
