### PR TITLE
Make installation command compatible with ZSH

### PR DESCRIPTION
**Pull request by tom-doerr**
## Description
This makes the command work in Zsh.

## Motivation and Context
Command fails if package is not in quotation marks:
```
➜  stable-baselines3 git:(fix_extra_install_command) ✗ pip install stable-baselines3[extra]  
zsh: no matches found: stable-baselines3[extra]
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Hey! Please remember to fill in the steps in the checklist (changelog, contributors).

Regarding PR: rather than updating the example of `pip install ...` command, I would remove the quotation marks and add a comment right after it saying something like "Note: Some shells like Zsh require quotation marks around brackets, i.e. `pip install [...]`".

**Comment by tom-doerr** [comment]
Adding a comment certainly makes sense when only few users are affected. However Zsh isn't the niche shell it used to be and now is even the default shell on Macs. Considering this, should I still add it as a comment?

**Comment by Miffyli** [comment]
Ah, good to know it has been set as default on Macs! :)

After discussing with @araffin we recommend to go with the "add a comment option" (a comment beside `pip install`  command that tells to use this way on Zsh, along with a long to [this stackoverflow](https://stackoverflow.com/a/30539963) answer in case users want to avoid similar errors in future). Update both installation documentation and README file.

**Comment by tom-doerr** [comment]
Should be ready to merge now.

**Review by araffin — APPROVED** [review]
LGTM =)

Next time, please open a "documentation" issue first ;)

**Pull request merged**
