### PR TITLE
 Add support for multidimensional `spaces.MultiBinary` observations 

### LINKED ISSUE #1073: MultiBinary not fully supported
The documentation says that `MultiBinary` is supported (at least for some of the RL agents), however it looks like the only supported case is `MultiBinary(n)` where `n` is an integer. The general case where `n` is a list of dimensions is not supported. See [gym doc](https://www.gymlibrary.dev/api/spaces/?highlight=multibinary#multibinary).

If the environments uses spaces of the form `MultiBinary([,,])` then an exception occurs at the following line because `observation_space.n` cannot be converted to an int:
https://github.com/DLR-RM/stable-baselines3/blob/b7456392acb921f68a6b9f894350c099726e5a55/stable_baselines3/common/preprocessing.py#L153

### PR DESCRIPTION
**Pull request by qgallouedec**
## Description

Fixes #1073
Returns the right shape instead of raising an error when parameter is multidimensional ``spaces.MultiBinary``.
**Note**: it does not make SB3 compatible with multidimensional ``spaces.MultiBinary``.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by qgallouedec** [comment]
To ease the review: all unittests pass on the master branch, except

- `tests/test_preprocessing.py::test_get_obs_shape_multidimensional_multibinary`

Before, it was throwing an error, now

```python
>>> get_obs_shape(spaces.MultiBinary([3, 2]))
(3, 2)
```

- `tests/test_preprocessing.py::test_preprocess_obs_multidiscrete`

It seems that `preprocess_obs` was not functional on the multidiscrete obs space:

before:

```python
>>> preprocess_obs(torch.tensor([2, 0], dtype=torch.long), spaces.MultiDiscrete([3, 2]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qgallouedec/stable-baselines3/stable_baselines3/common/preprocessing.py", line 115, in preprocess_obs
    for idx, obs_ in enumerate(th.split(obs.long(), 1, dim=1))
  File "/home/qgallouedec/stable-baselines3/env/lib/python3.10/site-packages/torch/functional.py", line 189, in split
    return tensor.split(split_size_or_sections, dim)
  File "/home/qgallouedec/stable-baselines3/env/lib/python3.10/site-packages/torch/_tensor.py", line 789, in split
    return torch._VF.split(self, split_size, dim)  # type: ignore[attr-defined]
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

now:

```python
>>> preprocess_obs(torch.tensor([2, 0], dtype=torch.long), spaces.MultiDiscrete([3, 2]))
tensor([0., 0., 1., 1., 0.])
```

**Comment by qgallouedec** [comment]
> this is on my todo list but not high priority 
agree, it's low priority

> to read the issue again and see what this PR does exactly

Basically, this does not solve the issue mentioned. It only makes the `get_obs_shape` function compatible with MultiBinary spaces. 

> if something else need to be updated like the env checker

I think there isn't, because it doesn't make sb3 compatible with MultiBinary envs. This PR is just a minor enhancement in this direction.

**Comment by araffin** [comment]
btw, is it intentional that it is still a draft?

**Review by araffin — APPROVED** [review]
@qgallouedec I did minor edits to add support for it, could you review my changes?

**Comment by qgallouedec** [comment]
It looks good :+1: . I thought there was more to it to support Multibinary observations

**Pull request merged**
