### PR TITLE
add tactile-gym to the list of projects using SB3

### PR DESCRIPTION
**Pull request by ac-93**
Update documentation to include tactile-gym project 

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Review by araffin — APPROVED** [review]
Thanks for the PR =)

**Comment by ac-93** [comment]
> PS: next time, please do not use master branch as I cannot push fixed to it...

Ah sorry my bad, won't do next time. Thanks for merging and all the work on this library!

**Comment by araffin** [comment]
> Ah sorry my bad, won't do next time. Thanks for merging and all the work on this library!

thanks =) See you maybe at CoRL too ;)

**Comment by ac-93** [comment]
> thanks =) See you maybe at CoRL too ;)

I'll keep an eye out for you :)

**Pull request merged**
