### PR TITLE
Removing dead code for handling time limits (see #829)

### LINKED ISSUE #829: [Question] Handling max steps / use of remove_time_limit_termination
Some environment will require a limit in the number of steps you can do to enforce periodic reset that are not necessary terminations, as explained in this former issue: https://github.com/hill-a/stable-baselines/issues/863

Apparently, the problem of handling such termination was mentionned, through the `info['TimeLimit.truncated']` flag that serves this purpose. @araffin also mentions some code handling that, using the `remove_time_limit_termination` flag.

However, in `master`, this flag doesn't seem to have any effect in the code. Looks like original snippet vanished:
https://github.com/DLR-RM/stable-baselines3/compare/feat/remove-timelimit

Does anybody knows if this is intended or if it was a merge / update issue ?

### PR DESCRIPTION
**Pull request by Gregwar**
## Description
Simple follow-up on #829, removing some dead code

## Motivation and Context
closes #829
- [X] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes
Technically none of below since it is just cleaning dead code

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [X] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [X] I have reformatted the code using `make format` (**required**)
- [X] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [X] I have ensured `make pytest` and `make type` both pass. (**required**)
- [X] I have checked that the documentation builds using `make doc` (**required**)

### CODE REVIEW

**Comment by Gregwar** [comment]
Didn't changed the changelog, not sure it desserves being there since it is a very small PR

**Comment by Miffyli** [comment]
Thanks! And yes, please update the changelog. Every little change and contribution deserves a mention :)

**Comment by Gregwar** [comment]
Ok I did so then

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
