### PR TITLE
Fix duplicate key error in HumanOutputFormat

### LINKED ISSUE #1078: [Bug] HumanOutputFormat raises error on duplicate keys
### 🐛 Bug

When using two keys that have different prefixes (tags) but the same key name, `HumanOutputFormat` will raise, complaining that the keys are duplicated.

### To Reproduce

```python
from stable_baselines3.common.logger import HumanOutputFormat
o = HumanOutputFormat(sys.stdout, max_length=50)
o.write({'key1/banana': 'value1', 'key2/banana': 'value2'}, {"key1/banana": None, "key2/banana": None})
```
Error:

```bash
Traceback (most recent call last):
  File "/Users/rocamonde/git/HumanCompatibleAI/imitation/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-ff13417a6e34>", line 2, in <module>
    o.write({'key1/banana': 'value1', 'key2/banana': 'value2'}, {"key1/banana": None, "key2/banana": None})
  File "/Users/rocamonde/git/HumanCompatibleAI/imitation/venv/lib/python3.9/site-packages/stable_baselines3/common/logger.py", line 183, in write
    raise ValueError(
ValueError: Key '   banana' truncated to '   banana' that already exists. Consider increasing `max_length`.
```

### Expected behavior

No error should raise. There's no reason why e.g. `model-1/loss` and `model-2/loss` should be disallowed key names.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

### PR DESCRIPTION
**Pull request by Rocamonde**
Fixes an error whereby keys are considered duplicate when they share the same key but have different prefixes (tags), since the tag is stripped off the key dictionary in HumanOutputFormat. 

## Description
We add the tag to the key in the keys dictionary, so we keep track of both the tag and the key without the tag to prevent this unwanted collision.

## Motivation and Context
Closes #1078.

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Review by qgallouedec — APPROVED** [review]

**Comment by qgallouedec** [comment]
Thank you for your contribution!

**Comment by Rocamonde** [comment]
Happy to help! @AdamGleave came up with the tuple implementation.

**Comment by Rocamonde** [comment]
@qgallouedec when do you think we can have a release that includes this? This is a blocking bug for our work in imitation across two PRs. It would be nice to have a 1.6.1. that includes these bug fixes. Happy to help with that!

**Comment by araffin** [comment]
Hello,
thanks for fixing the issue =)
(it was actually a known bug: https://github.com/DLR-RM/stable-baselines3/issues/256)
Does it solve it also for the other output formats?

>  It would be nice to have a 1.6.1. that includes these bug fixes

Actually, I wanted to do that as we fixed many bugs (including in contrib) recently.
Will try to release it this week ;) (please ping me next monday if you didn't see the release)

**Pull request merged**
