### PR TITLE
Update ppo.py

### PR DESCRIPTION
**Pull request by zeeshanalipanhwar**
The initialization of the inherited class must take `_init_setup_model` as the `_init_setup_model` that the initialization function of the inheriting class is getting. Note the order agent files might require the same update.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Please open an issue discussing the bug/issue/enhancement (remember to fill out the issue template). Only fixes for obvious typos are accepted as PRs directly :)

**Comment by zeeshanalipanhwar** [comment]
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_6988/1580690086.py in <module>
      1 agent = PPO(policy="MlpPolicy", env=env_train, n_steps=2048*8, batch_size=64*8, n_epochs=10//5,
      2             tensorboard_log='../log', verbose=1, device='cuda', _init_setup_model=True)
----> 3 agent.train()

~/anaconda3/envs/sb3/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py in train(self)
    170         self.policy.set_training_mode(True)
    171         # Update optimizer learning rate
--> 172         self._update_learning_rate(self.policy.optimizer)
    173         # Compute current clip range
    174         clip_range = self.clip_range(self._current_progress_remaining)

~/anaconda3/envs/sb3/lib/python3.7/site-packages/stable_baselines3/common/base_class.py in _update_learning_rate(self, optimizers)
    295         """
    296         # Log the current learning rate
--> 297         self.logger.record("train/learning_rate", self.lr_schedule(self._current_progress_remaining))
    298 
    299         if not isinstance(optimizers, list):

AttributeError: 'NoneType' object has no attribute 'record'


```

**Comment by zeeshanalipanhwar** [comment]
> ```
> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> /tmp/ipykernel_6988/1580690086.py in <module>
>       1 agent = PPO(policy="MlpPolicy", env=env_train, n_steps=2048*8, batch_size=64*8, n_epochs=10//5,
>       2             tensorboard_log='../log', verbose=1, device='cuda', _init_setup_model=True)
> ----> 3 agent.train()
> 
> ~/anaconda3/envs/sb3/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py in train(self)
>     170         self.policy.set_training_mode(True)
>     171         # Update optimizer learning rate
> --> 172         self._update_learning_rate(self.policy.optimizer)
>     173         # Compute current clip range
>     174         clip_range = self.clip_range(self._current_progress_remaining)
> 
> ~/anaconda3/envs/sb3/lib/python3.7/site-packages/stable_baselines3/common/base_class.py in _update_learning_rate(self, optimizers)
>     295         """
>     296         # Log the current learning rate
> --> 297         self.logger.record("train/learning_rate", self.lr_schedule(self._current_progress_remaining))
>     298 
>     299         if not isinstance(optimizers, list):
> 
> AttributeError: 'NoneType' object has no attribute 'record'
> ```

self.logger is initialized based on the Boolean parameter `_init_setup_model`.

**Comment by Miffyli** [comment]
Please open an issue and fill the template with minimal code to reproduce the error. I can not reproduce the error from this alone.

**Comment by zeeshanalipanhwar** [comment]
> Please open an issue and fill the template with minimal code to reproduce the error. I can not reproduce the error from this alone.

Done, kindly review it.

**Comment by araffin** [comment]
This is intentional as PPO has additional checks in the constructor and `_init_setup_model ` is used afterward.

**Pull request closed without merging**
