### PR TITLE
Fix random seed int32 for Windows

### LINKED ISSUE #1579: [Bug]: ValueError: high is out of bounds for int32
### 🐛 Bug

Hi.

SB3 v2.0
The following code causes an error on Win64.  

https://github.com/DLR-RM/stable-baselines3/blob/472ff8edb815070c405da913dcbe64c1a06e0e7d/stable_baselines3/common/vec_env/base_vec_env.py#L281

The reason is:
https://stackoverflow.com/a/36279549/2965317

Steps to reproduce:
Just create a Env calling make_vec_env on Windows x64

If I set the dtype=np.int64 everting works. On Linux runs without changes.

It was introduced by this commit: https://github.com/DLR-RM/stable-baselines3/commit/9c338f917a822c8be13b1aa9f7b2319770481b62#diff-fbbbeff0096dec393a26abdfb588b08aede5e15e5b9a0e7ff4f5ea45fc031896

### To Reproduce

```python
from stable_baselines3 import ...
make_vec_env("CartPole-v1", n_envs=2)
```

### Relevant log output / Error message

```shell
seed = np.random.randint(0, 2**32 - 1)
File "mtrand.pyx", line 746, in numpy.random.mtrand.RandomState.randint
File "_bounded_integers.pyx", line 1336, in numpy.random._bounded_integers._rand_int32
ValueError: high is out of bounds for int32
```
```


### System Info

- OS: Windows-10-10.0.22621-SP0 10.0.22621
- Python: 3.10.10
- Stable-Baselines3: 2.0.0
- PyTorch: 2.0.0
- GPU Enabled: True
- Numpy: 1.23.5
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.21.0

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

### PR DESCRIPTION
**Pull request by PatrickHelm**
## Description

I recognized the error described in #1579 while running the tests for another pull request on Windows. To fix it, I changed `high` in `np.random.randint` from `2**32-1` to `2**31-1.` The solution proposed by @MikhailGerasimov in #1579 did not work as Gymnasium does not accept numpy integers as seeds. 

## Motivation and Context

closes #1579
- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have opened an associated PR on the [SB3-Contrib repository](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) (if necessary)
- [ ] I have opened an associated PR on the [RL-Zoo3 repository](https://github.com/DLR-RM/rl-baselines3-zoo) (if necessary)
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [x] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by araffin** [comment]
> he solution proposed by @MikhailGerasimov in https://github.com/DLR-RM/stable-baselines3/issues/1579 did not work as Gymnasium does not accept numpy integers as seeds.

Hmm, does an explicit cast `int(np.random(..., dtype=np.int64))` works? (the question is `int(2**32 - 1)` of the correct type on windows?

**Comment by MikhailGerasimov** [comment]
I would suggest a small improvement to eliminate the magic number.
`int(np.random.randint(0, np.iinfo(np.uint32).max, dtype=np.uint32)) `

2**32 - 1 ==  np.iinfo(np.uint32).max == 4294967295 

> (the question: is int(2**32 - 1) of the correct type on windows?)

The issue lies not with Windows, but with NumPy. It uses different implicit types for Windows and Linux. On Windows, it's a signed 32-bit integer, while on Linux, it's a 64-bit integer. By explicitly setting the type, everything should function correctly.

On Windows
print(np.iinfo(np.int_).max) == 2147483647
On Linux
print(np.iinfo(np.int_).max) == 9223372036854775807

https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html

**Comment by MikhailGerasimov** [comment]
I would suggest a small improvement to eliminate the magic number.
`int(np.random.randint(0, np.iinfo(np.uint32).max, dtype=np.uint32)) `

2**32 - 1 ==  np.iinfo(np.uint32).max == 4294967295 

> (the question: is int(2**32 - 1) of the correct type on windows?)

The issue lies not with Windows, but with NumPy. It uses different implicit types for Windows and Linux. On Windows, it's a signed 32-bit integer, while on Linux, it's a 64-bit integer. By explicitly setting the type, everything should function correctly.

On Windows
print(np.iinfo(np.int_).max) == 2147483647
On Linux
print(np.iinfo(np.int_).max) == 9223372036854775807

https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html

**Comment by araffin** [comment]
@PatrickHelm could you test @MikhailGerasimov solution on windows?

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
