### PR TITLE
Fix PPO logging of clip_fractions

### LINKED ISSUE #149: PPO clip_fraction logging bug
I think I've found a minor bug in your PPO algo realisation.
See, in the main class PPO(OnPolicyAlgorithm), def train() function, after all the loops and main code there is a logging part:

logger.record("train/entropy_loss", np.mean(entropy_losses))
logger.record("train/policy_gradient_loss", np.mean(pg_losses))
logger.record("train/value_loss", np.mean(value_losses))
logger.record("train/approx_kl", np.mean(approx_kl_divs))
logger.record("train/clip_fraction", np.mean(clip_fraction))
logger.record("train/loss", loss.item())
logger.record("train/explained_variance", explained_var)

take a closer look at logging variables. While np.mean is used over lists of accumulated values everywhere, for clip fraction you have np.mean(clip_fraction), NOT clip_fractions. So you always log the fraction from the last rollout data batch only, not avg for the full algo iteration.

I'm pretty certain I'm right. I can make a PR correcting it if you agree.

### PR DESCRIPTION
**Pull request by diditforlulz273**
## Description

I think I've found a minor bug in your PPO algo realisation.
See, in the main class PPO(OnPolicyAlgorithm), def train() function, after all the loops and main code there is a logging part:

logger.record("train/entropy_loss", np.mean(entropy_losses))
logger.record("train/policy_gradient_loss", np.mean(pg_losses))
logger.record("train/value_loss", np.mean(value_losses))
logger.record("train/approx_kl", np.mean(approx_kl_divs))
logger.record("train/clip_fraction", np.mean(clip_fraction))
logger.record("train/loss", loss.item())
logger.record("train/explained_variance", explained_var)

take a closer look at logging variables. While np.mean is used over lists of accumulated values everywhere, for clip fraction you have np.mean(clip_fraction), NOT clip_fractions. So you always log the fraction from the last rollout data batch only, not avg for the full algo iteration.

full description is in Issue here: [https://github.com/DLR-RM/stable-baselines3/issues/149](https://github.com/DLR-RM/stable-baselines3/issues/149)

## Motivation and Context

closes #149 

- [X] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [X] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ NOPE ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [X] I have reformatted the code using `make format` (**required**)
- [X] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [X] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by diditforlulz273** [comment]
lol@ failing code style checks in 7 different files after changing a single line of code in one file

**Comment by araffin** [comment]
> lol@ failing code style checks in 7 different files after changing a single line of code in one file.
> This couldn't be a problem of my commit. How could it be fixed?

Fixed ;)
Please don't forget to complete all required items of the checklist (cf CONTRIBUTING guide).

**Review by araffin — APPROVED** [review]
LGTM, I updated the changelog for you this time, please do it next time ;)

**Comment by diditforlulz273** [comment]
Ah thanks, got really busy with work and forgot about my PR completely!

**Pull request merged**
