### PR TITLE
Update docs (custom policy, type hints)

### LINKED ISSUE #144: Custom Policy Example (Question)
Hello,

First of all thank you for the great library. In stable-baselines there was an example of custom policy (class CustomPolicy(ActorCriticPolicy)). I was wondering if it was possible to add the same for stable-baselines3. I want to use MultiHeadAttention module and have a separate net for value function and policy (PPO). Not sure what the best way to implement the custom policy is.

### LINKED ISSUE #168: [bug] Unexpected keyword argument "use_sde" in custom policy
I'm implementing an agent for a custom environment (it passed check_env), custom networks and custom ActorCriticPolicy. The environment has an MultiBinary(10) action space. Find below a code example.

I'm using self-implemented feature extractor and head networks inherit from BaseFeaturesExtractor and nn.Module respectively. When A2C or PPO tries to create the policy, the policy_kwargs argument fails. In the ActorCriticPolicy class use_sde is False by default, so I don't know what the problem may be.

```python
from lib import CustomEnv, CustomCNN, CustomNetwork
from stable_baselines3.common.policies import ActorCriticPolicy
from stable_baselines3.a2c import A2C

class CustomPolicy(ActorCriticPolicy):
    def __init__(
        self,
        observation_space: gym.spaces.Space,
        action_space: gym.spaces.Space,
        lr_schedule: Callable[[float], float],
    ):
        super(CustomPolicy, self).__init__(
            observation_space,
            action_space,
            lr_schedule,
            features_extractor_class=CustomCNN,
            normalize_images=False)

    def _build(self, lr_schedule: Callable[[float], float]) -> None:
        # Policy and value heads network
        self.mlp_extractor = CustomNetwork(self.features_dim)
        ...

env = CustomEnv()
agent = CustomPolicy(env.observation_space, env.action_space, lr_)
model = A2C(agent, env)
model.learn(1e5)
```

I got the following error:

```bash
Traceback (most recent call last):
  File "agent.py", line 131, in <module>
    model = A2C(agent, env)
  File "/home/jajimer/lib/python3.7/site-packages/stable_baselines3/a2c/a2c.py", line 109, in __init__
    self._setup_model()
  File "/home/jajimer/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 120, in _setup_model
    **self.policy_kwargs  # pytype:disable=not-instantiable
  File "/home/jajimer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'use_sde'
```

**System Info**
My environment:
 * pip installation
 * Running on CPU and Ubuntu 18.04.2 LTS
 * Python version 3.7.3
 * PyTorch version 1.6.0
 * Gym version 0.17.2

Any help will be appreciated. Thanks in advance.

### PR DESCRIPTION
**Pull request by araffin**
## Description

- Add custom feature extractor example
- Add full custom policy example for on-policy algorithms
- Re-enable autodoc type hint extension (looks much nicer with the latest version) and fix some issues due to that

You can see the difference with those links:
current doc: https://stable-baselines3.readthedocs.io/en/master/modules/td3.html#parameters
this PR: https://stable-baselines3.readthedocs.io/en/doc-custom-policy/modules/td3.html#parameters

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

Addresses part of #10 and #166 
closes #144 
closes #168

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Looking good and indeed much cleaner docs! Some comments though:

- Does the example run as expected (wondering because of #168)?
- With hints automatically included from type hinting, we should clean up docstrings from type hints. I think it should be included with this update or #166. 
- Type hints in docs would be cleaner if parentheses were also formatted with code-like style, but I figure this goes to sphinx side where modifications can be difficult.

**Comment by araffin** [comment]
>Does the example run as expected (wondering because of #168)?

actually, the current example runs but is simpler than #168
that's why i do not close #166
i will probably add a full advance usage today then.


for your last two points, i made myself the same remarks but i would address them in a separate PR to keep that one small ;)

**Review by Miffyli — APPROVED** [review]
In that case LGTM! I added the two remarks to respective issues as TODOs.

**Comment by pengzhi1998** [comment]
Sorry to bother you.

I'm constructing a different network architecture with self-attention. Though my attention block is not for dealing with sequences but is using sigmoid which is not MLP. And my actor network and the critic network are not sharing the parameters.

I'm wondering whether I could use [advanced custom policy](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#advanced-example) to construct my attention block for the PPO network with the function `_build_mlp_extractor` as shown in the example?

**Comment by Miffyli** [comment]
@pengzhi1998 Hey. We unfortunately do not have time to offer custom tech support for custom scenarios. For your scenario, you should use the fully custom policy (which you found already) to define things from ground-up. That is the most customizable way: modifying feature extractor can be limiting.

PS: next time please open a new issue for questions instead of continuing a closed PR :)

**Pull request merged**
