### PR TITLE
Corrected DictReplayBuffer observation dtype #484

### LINKED ISSUE #484: [Bug] Wrong DictReplayBuffer observation dtype
### 🐛 Bug

DictReplayBuffer does not set the dtype for the observation buffer according to the environment observation_space.
The issue can be solved as in [this commit](https://github.com/c-rizz/stable-baselines3/commit/eef6ec14412961df9bf20b47e4d63f821918238b)
I'm not sure if the same issue is present in DictRolloutBuffer, from the code it looks like it but I did not try it.

### To Reproduce

I couldn't recreate a simple example, sorry. I found this out working on a relatively big project that I'm working on that uses stable_baselines. It is not published and not public (yet), so I cannot provide an example from that. However I believe the issue is quite clear. I think that in examples such as [the one in docs](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html?highlight=dict#dict-observations) the problem is being hidden by the observation preprocessing. But it could still lead to performance degradation. I believe right now all observations are being represented in the buffer as float64 (default dtype in [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html))

### Expected behavior

Correct dtypes being used.

### System Info

 * Installed via pip
 * 1080 Ti GPU
 * Python 3.7
 * PyTorch 1.8.0
 * Gym 0.17.1
 * Numpy 1.20.3

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

### PR DESCRIPTION
**Pull request by c-rizz**
## Description
Changed observation buffers definition in DictReplayBuffer to use the same dytpe as specified by the observation_space.

## Motivation and Context
Without this change all observation buffers were always using float64, this leads to higher memory consumption and unnecessary casts.
Closes #484 
- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

### Question:
Should I put anything in the changelog? Quite a minor change and on a feature new to this release, not sure what I could write

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for the PR and yes please update the changelog ;)

**Comment by c-rizz** [comment]
Hi, ok, added a line in the bugfixes list for the latest version and my username at the end

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Comment by c-rizz** [comment]
You're welcome! Thanks to you all for the great library!

**Pull request merged**
