### PR TITLE
Separate feature extractor networks for DQN networks

### LINKED ISSUE #131: [Bug] Optimized Polyak update not equivalent for CnnPolicy
The following code works for `MlpPolicy` but fail with CNN.

```python
import torch as th

from stable_baselines3 import DQN
from stable_baselines3.common.cmd_util import make_atari_env
from stable_baselines3.common.utils import polyak_update

tau = 0.1

model = DQN('CnnPolicy', make_atari_env('BreakoutNoFrameskip-v4', 1), learning_starts=0,
      target_update_interval=250, verbose=1, seed=0,
      train_freq=100, buffer_size=1000)

model_2 = DQN('CnnPolicy', make_atari_env('BreakoutNoFrameskip-v4', 1), learning_starts=0,
      target_update_interval=250, verbose=1, seed=0,
      train_freq=100, buffer_size=1000)

polyak_update(model.q_net.parameters(), model.q_net_target.parameters(), tau)
with th.no_grad():
    for param, target_param in zip(model_2.q_net.parameters(), model_2.q_net_target.parameters()):
        target_param.data.copy_(tau * param.data + (1 - tau) * target_param.data)

for param, target_param in zip(model.q_net_target.parameters(), model_2.q_net_target.parameters()):
    assert th.allclose(param, target_param)
```

Introduced in #106 

Pinging @PartiallyTyped 

EDIT: this optimization is maybe not needed anymore, see https://github.com/DLR-RM/stable-baselines3/issues/122#issuecomment-666521802

### PR DESCRIPTION
**Pull request by Miffyli**
Closes #131 

## Description
DQN main and target network accidentally shared feature extractor network. This fix creates new feature extractor each time new QNetwork is made.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [X] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [X] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [X] I have reformatted the code using `make format` (**required**)
- [X] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [X] I have ensured `make pytest` and `make type` both pass. (**required**)

### CODE REVIEW

**Comment by araffin** [comment]
Nice catch, but it was working before?

I think we may have the issue with SAC/TD3 too then.

**Comment by Miffyli** [comment]
> Nice catch, but it was working before?

I do not see how it could have worked before, unless somewhere along the line the models got cloned or the references to data they use were separated (not sure how that could happen, either...).

**Comment by PartiallyTyped** [comment]
If the extractor isn’t flatten, then using the “is” operator with the .parameters() function should catch it.

**Comment by araffin** [comment]
>If the extractor isn’t flatten, then using the “is” operator with the .parameters() function should catch it.

Ok, I think I will delay the test to SAC/TD3 fix, as this is a hotfix for DQN.

**Pull request merged**
